services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    volumes:
      - ./api:/app
      - ./app_data:/app/app_data
    restart: unless-stopped
    ports:
      - 5000:5000
  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    volumes:
      - ./client:/app
    restart: unless-stopped
    ports:
      - 5173:5173
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: showcase
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
