services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 2000:5000
    
    user: node
    volumes:
      - ./app_data:/app/dist/app_data
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        restart: true

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      VITE_API_URL: http://192.168.100.137:5000
    ports:
      - 5173:5173
    depends_on:
      - api

  db:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - prod_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: showcase
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d showcase
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  proxy:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    build:
      context: ./proxy
      dockerfile: dockerfile
    depends_on:
      - api
      - client

volumes:
  prod_pgdata:
