services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    volumes:
      - ./api:/app
      - ./app_data:/app/app_data
    restart: unless-stopped
    ports:
      - 5000:5000
    user: "node"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    volumes:
      - ./client:/app
    restart: unless-stopped
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://192.168.100.137:5000
    depends_on:
      - api

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: showcase
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d showcase
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
