FROM node:20.12.1
USER node
#RUN apt update && apt -y upgrade
#RUN apt -y install ffmpeg
WORKDIR /app
COPY . /app
RUN npm install
RUN npm run build
WORKDIR /app/dist
COPY startup.prod.sh /app/dist/
RUN npm install pm2 -g
ENTRYPOINT [ "./startup.prod.sh" ]
