FROM node:20.12.1 AS build1
EXPOSE 5000
RUN apt update && apt -y upgrade
RUN apt -y install ffmpeg
WORKDIR /app
COPY . /app
RUN npm install
RUN npm run build

FROM nginx:1.27.1
EXPOSE 8080
COPY --from=build1 /app/dist /usr/share/nginx/html