FROM node:20.12.1
RUN apt update && apt -y upgrade
RUN apt -y install ffmpeg
RUN echo umask 0000 >> ~/.bashrc
EXPOSE 5000
WORKDIR /app
COPY . /app
RUN npm install --include dev
USER 1000
ENTRYPOINT [ "./startup.sh" ]
